import type { OxlintConfig } from "oxlint";

export const config = {
  plugins: ["eslint", "import", "node", "oxc", "promise", "typescript", "unicorn", "vitest"],
  env: {
    browser: true,
    node: true,
  },
  options: {
    reportUnusedDisableDirectives: "error",
    typeAware: true,
    typeCheck: true,
  },
  settings: {
    vitest: {
      typecheck: true,
    },
  },
  ignorePatterns: [
    "**/.vite-hooks/**",
    "**/build/**",
    "**/coverage/**",
    "**/dist/**",
    "**/node_modules/**",
  ],
  rules: {
    "eslint/accessor-pairs": ["error", { enforceForClassMembers: true }],
    "eslint/array-callback-return": ["error", { allowImplicit: true }],
    "eslint/arrow-body-style": "off",
    "eslint/block-scoped-var": "off",
    "eslint/capitalized-comments": "off",
    "eslint/class-methods-use-this": "off",
    "eslint/complexity": "off",
    "eslint/constructor-super": "off",
    "eslint/curly": ["error", "all"],
    "eslint/default-case": "off",
    "eslint/default-case-last": "error",
    "eslint/default-param-last": "error",
    "eslint/eqeqeq": "error",
    "eslint/for-direction": "error",
    "eslint/func-name-matching": ["error", "never", { considerPropertyDescriptor: true }],
    "eslint/func-names": "off",
    "eslint/func-style": ["error", "declaration", { allowArrowFunctions: true }],
    "eslint/getter-return": "error",
    "eslint/grouped-accessor-pairs": ["error", "getBeforeSet"],
    "eslint/guard-for-in": "error",
    "eslint/id-denylist": "off",
    "eslint/id-length": "off",
    "eslint/id-match": "off",
    "eslint/init-declarations": "off",
    "eslint/logical-assignment-operators": "off",
    "eslint/max-classes-per-file": "off",
    "eslint/max-depth": "off",
    "eslint/max-lines": "off",
    "eslint/max-lines-per-function": "off",
    "eslint/max-nested-callbacks": "off",
    "eslint/max-params": "off",
    "eslint/max-statements": "off",
    "eslint/new-cap": "off",
    "eslint/no-alert": "error",
    "eslint/no-array-constructor": "error",
    "eslint/no-async-promise-executor": "error",
    "eslint/no-await-in-loop": "error",
    "eslint/no-bitwise": "error",
    "eslint/no-caller": "error",
    "eslint/no-case-declarations": "error",
    "eslint/no-class-assign": "off",
    "eslint/no-compare-neg-zero": "error",
    "eslint/no-cond-assign": "error",
    "eslint/no-console": "error",
    "eslint/no-const-assign": "off",
    "eslint/no-constant-binary-expression": "error",
    "eslint/no-constant-condition": "error",
    "eslint/no-constructor-return": "error",
    "eslint/no-continue": "off",
    "eslint/no-control-regex": "error",
    "eslint/no-debugger": "error",
    "eslint/no-delete-var": "off",
    "eslint/no-div-regex": "off",
    "eslint/no-dupe-class-members": "off",
    "eslint/no-dupe-else-if": "error",
    "eslint/no-dupe-keys": "off",
    "eslint/no-duplicate-case": "error",
    "eslint/no-duplicate-imports": "off",
    "eslint/no-else-return": ["error", { allowElseIf: false }],
    "eslint/no-empty": ["error", { allowEmptyCatch: true }],
    "eslint/no-empty-character-class": "error",
    "eslint/no-empty-function": "error",
    "eslint/no-empty-pattern": "error",
    "eslint/no-empty-static-block": "error",
    "eslint/no-eq-null": "error",
    "eslint/no-eval": "error",
    "eslint/no-ex-assign": "error",
    "eslint/no-extend-native": "error",
    "eslint/no-extra-bind": "error",
    "eslint/no-extra-boolean-cast": "error",
    "eslint/no-extra-label": "error",
    "eslint/no-fallthrough": "off",
    "eslint/no-func-assign": "off",
    "eslint/no-global-assign": "error",
    "eslint/no-implicit-coercion": "error",
    "eslint/no-implicit-globals": "error",
    "eslint/no-implied-eval": "error",
    "eslint/no-import-assign": "off",
    "eslint/no-inline-comments": "off",
    "eslint/no-inner-declarations": "off",
    "eslint/no-invalid-regexp": "error",
    "eslint/no-irregular-whitespace": "off",
    "eslint/no-iterator": "off",
    "eslint/no-label-var": "off",
    "eslint/no-labels": "off",
    "eslint/no-lone-blocks": "off",
    "eslint/no-lonely-if": "error",
    "eslint/no-loop-func": "error",
    "eslint/no-loss-of-precision": "error",
    "eslint/no-magic-numbers": "off",
    "eslint/no-misleading-character-class": "error",
    "eslint/no-multi-assign": "error",
    "eslint/no-multi-str": "off",
    "eslint/no-negated-condition": "off",
    "eslint/no-nested-ternary": "off",
    "eslint/no-new": "off",
    "eslint/no-new-func": "error",
    "eslint/no-new-native-nonconstructor": "off",
    "eslint/no-new-wrappers": "error",
    "eslint/no-nonoctal-decimal-escape": "error",
    "eslint/no-obj-calls": "off",
    "eslint/no-object-constructor": "error",
    "eslint/no-param-reassign": "error",
    "eslint/no-plusplus": "off",
    "eslint/no-promise-executor-return": "error",
    "eslint/no-proto": "error",
    "eslint/no-prototype-builtins": "off",
    "eslint/no-redeclare": "off",
    "eslint/no-regex-spaces": "error",
    "eslint/no-restricted-exports": "off",
    "eslint/no-restricted-globals": "off",
    "eslint/no-restricted-imports": "off",
    "eslint/no-restricted-properties": "off",
    "eslint/no-return-assign": ["error", "always"],
    "eslint/no-script-url": "error",
    "eslint/no-self-assign": ["error", { props: true }],
    "eslint/no-self-compare": "error",
    "eslint/no-sequences": "error",
    "eslint/no-setter-return": "off",
    "eslint/no-shadow": "off",
    "eslint/no-shadow-restricted-names": "error",
    "eslint/no-sparse-arrays": "error",
    "eslint/no-template-curly-in-string": "error",
    "eslint/no-ternary": "off",
    "eslint/no-this-before-super": "off",
    "eslint/no-throw-literal": "error",
    "eslint/no-unassigned-vars": "error",
    "eslint/no-undef": "off",
    "eslint/no-undefined": "off",
    "eslint/no-underscore-dangle": "off",
    "eslint/no-unexpected-multiline": "off",
    "eslint/no-unmodified-loop-condition": "error",
    "eslint/no-unneeded-ternary": "error",
    "eslint/no-unreachable": "off",
    "eslint/no-unsafe-finally": "error",
    "eslint/no-unsafe-negation": "error",
    "eslint/no-unsafe-optional-chaining": ["error", { disallowArithmeticOperators: true }],
    "eslint/no-unused-expressions": ["error", { enforceForJSX: true }],
    "eslint/no-unused-labels": "error",
    "eslint/no-unused-private-class-members": "error",
    "eslint/no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        varsIgnorePattern: "^_",
      },
    ],
    "eslint/no-use-before-define": "off",
    "eslint/no-useless-assignment": "error",
    "eslint/no-useless-backreference": "error",
    "eslint/no-useless-call": "error",
    "eslint/no-useless-catch": "error",
    "eslint/no-useless-computed-key": "error",
    "eslint/no-useless-concat": "error",
    "eslint/no-useless-constructor": "off",
    "eslint/no-useless-escape": "error",
    "eslint/no-useless-rename": "error",
    "eslint/no-useless-return": "error",
    "eslint/no-var": "error",
    "eslint/no-void": "off",
    "eslint/no-warning-comments": "error",
    "eslint/no-with": "error",
    "eslint/object-shorthand": ["error", "always"],
    "eslint/one-var": "off",
    "eslint/operator-assignment": ["error", "always"],
    "eslint/prefer-arrow-callback": ["error", { allowNamedFunctions: true }],
    "eslint/prefer-const": "error",
    "eslint/prefer-destructuring": "error",
    "eslint/prefer-exponentiation-operator": "error",
    "eslint/prefer-named-capture-group": "off",
    "eslint/prefer-numeric-literals": "off",
    "eslint/prefer-object-has-own": "error",
    "eslint/prefer-object-spread": "error",
    "eslint/prefer-promise-reject-errors": "error",
    "eslint/prefer-regex-literals": "error",
    "eslint/prefer-rest-params": "error",
    "eslint/prefer-spread": "error",
    "eslint/prefer-template": "error",
    "eslint/preserve-caught-error": "error",
    "eslint/radix": "error",
    "eslint/require-await": "off",
    "eslint/require-unicode-regexp": "off",
    "eslint/require-yield": "error",
    "eslint/sort-imports": "off", // fmt.sortImports
    "eslint/sort-keys": "off",
    "eslint/sort-vars": "off",
    "eslint/symbol-description": "error",
    "eslint/unicode-bom": ["error", "never"],
    "eslint/use-isnan": "error",
    "eslint/valid-typeof": ["error", { requireStringLiterals: false }],
    "eslint/vars-on-top": "off",
    "eslint/yoda": ["error", "never", { exceptRange: true }],
    "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
    "import/default": "error",
    "import/exports-last": "off",
    "import/extensions": "off",
    "import/first": "error",
    "import/group-exports": "off",
    "import/max-dependencies": "off",
    "import/namespace": "error",
    "import/newline-after-import": "error", // oxfmt preserves a trailing import blank, does not insert one
    "import/no-absolute-path": "error",
    "import/no-amd": "off",
    "import/no-anonymous-default-export": "error",
    "import/no-commonjs": ["error", { allowConditionalRequire: false }],
    "import/no-cycle": "error",
    "import/no-default-export": "off",
    "import/no-duplicates": "error",
    "import/no-dynamic-require": "off",
    "import/no-empty-named-blocks": "error",
    "import/no-mutable-exports": "error",
    "import/no-named-as-default": "error",
    "import/no-named-as-default-member": "error",
    "import/no-named-default": "error",
    "import/no-named-export": "off",
    "import/no-namespace": "off",
    "import/no-nodejs-modules": "off",
    "import/no-relative-parent-imports": "off",
    "import/no-self-import": "error",
    "import/no-unassigned-import": "error",
    "import/no-webpack-loader-syntax": "off",
    "import/prefer-default-export": "off",
    "import/unambiguous": "error",
    "node/callback-return": "off",
    "node/exports-style": "off",
    "node/global-require": "off",
    "node/handle-callback-err": ["error", "error"],
    "node/no-exports-assign": "off",
    "node/no-mixed-requires": "off",
    "node/no-new-require": "off",
    "node/no-path-concat": "error",
    "node/no-process-env": "off",
    "node/no-sync": "off",
    "node/no-top-level-await": "off",
    "oxc/approx-constant": "error",
    "oxc/bad-array-method-on-arguments": "error",
    "oxc/bad-bitwise-operator": "error",
    "oxc/bad-char-at-comparison": "error",
    "oxc/bad-comparison-sequence": "error",
    "oxc/bad-match-all-arg": "error",
    "oxc/bad-min-max-func": "error",
    "oxc/bad-object-literal-comparison": "error",
    "oxc/bad-replace-all-arg": "error",
    "oxc/branches-sharing-code": "error",
    "oxc/const-comparisons": "error",
    "oxc/double-comparisons": "error",
    "oxc/erasing-op": "error",
    "oxc/misrefactored-assign-op": "error",
    "oxc/missing-throw": "error",
    "oxc/no-accumulating-spread": "error",
    "oxc/no-async-await": "off",
    "oxc/no-async-endpoint-handlers": "off",
    "oxc/no-barrel-file": "off",
    "oxc/no-const-enum": "off",
    "oxc/no-map-spread": "error",
    "oxc/no-optional-chaining": "off",
    "oxc/no-rest-spread-properties": "off",
    "oxc/no-this-in-exported-function": "error",
    "oxc/number-arg-out-of-range": "error",
    "oxc/only-used-in-recursion": "error",
    "oxc/uninvoked-array-callback": "error",
    "promise/always-return": "error",
    "promise/avoid-new": "off",
    "promise/catch-or-return": "error",
    "promise/no-callback-in-promise": "error",
    "promise/no-multiple-resolved": "error",
    "promise/no-nesting": "error",
    "promise/no-new-statics": "error",
    "promise/no-promise-in-callback": "error",
    "promise/no-return-in-finally": "error",
    "promise/no-return-wrap": ["error", { allowReject: true }],
    "promise/param-names": "error",
    "promise/prefer-await-to-callbacks": "off",
    "promise/prefer-await-to-then": "error",
    "promise/prefer-catch": "error",
    "promise/spec-only": "error",
    "promise/valid-params": "error",
    "typescript/adjacent-overload-signatures": "error",
    "typescript/array-type": [
      "error",
      {
        default: "array-simple",
        readonly: "generic",
      },
    ],
    "typescript/await-thenable": "error",
    "typescript/ban-ts-comment": [
      "error",
      {
        "ts-check": true,
        "ts-expect-error": "allow-with-description",
        "ts-ignore": true,
        "ts-nocheck": true,
      },
    ],
    "typescript/ban-tslint-comment": "error",
    "typescript/ban-types": "off",
    "typescript/class-literal-property-style": ["error", "fields"],
    "typescript/consistent-generic-constructors": ["error", "constructor"],
    "typescript/consistent-indexed-object-style": ["error", "record"],
    "typescript/consistent-return": "error",
    "typescript/consistent-type-assertions": ["error", { assertionStyle: "as" }],
    "typescript/consistent-type-definitions": ["error", "type"],
    "typescript/consistent-type-exports": "error",
    "typescript/consistent-type-imports": [
      "error",
      {
        fixStyle: "separate-type-imports",
        prefer: "type-imports",
      },
    ],
    "typescript/dot-notation": "error",
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-member-accessibility": ["error", { accessibility: "no-public" }],
    "typescript/explicit-module-boundary-types": [
      "error",
      { allowArgumentsExplicitlyTypedAsAny: false },
    ],
    "typescript/method-signature-style": ["error", "property"],
    "typescript/no-array-delete": "error",
    "typescript/no-base-to-string": "error",
    "typescript/no-confusing-non-null-assertion": "error",
    "typescript/no-confusing-void-expression": ["error", { ignoreArrowShorthand: true }],
    "typescript/no-deprecated": "error",
    "typescript/no-duplicate-enum-values": "error",
    "typescript/no-duplicate-type-constituents": "error",
    "typescript/no-dynamic-delete": "error",
    "typescript/no-empty-interface": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-extra-non-null-assertion": "error",
    "typescript/no-extraneous-class": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-for-in-array": "error",
    "typescript/no-implied-eval": "error",
    "typescript/no-import-type-side-effects": "error",
    "typescript/no-inferrable-types": "error",
    "typescript/no-invalid-void-type": "error",
    "typescript/no-meaningless-void-operator": "error",
    "typescript/no-misused-new": "error",
    "typescript/no-misused-promises": [
      "error",
      {
        checksConditionals: true,
        checksVoidReturn: true,
      },
    ],
    "typescript/no-misused-spread": "error",
    "typescript/no-mixed-enums": "error",
    "typescript/no-namespace": ["error", { allowDeclarations: true }],
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/no-redundant-type-constituents": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-restricted-types": [
      "error",
      {
        types: {
          "[]": true,
          null: true,
          object: true,
        },
      },
    ],
    "typescript/no-this-alias": "error",
    "typescript/no-unnecessary-boolean-literal-compare": "error",
    "typescript/no-unnecessary-parameter-property-assignment": "error",
    "typescript/no-unnecessary-qualifier": "error",
    "typescript/no-unnecessary-template-expression": "error",
    "typescript/no-unnecessary-type-arguments": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unnecessary-type-conversion": "error",
    "typescript/no-unnecessary-type-parameters": "error",
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-declaration-merging": "error",
    "typescript/no-unsafe-enum-comparison": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/no-unsafe-type-assertion": "error",
    "typescript/no-unsafe-unary-minus": "error",
    "typescript/no-useless-default-assignment": "error",
    "typescript/no-useless-empty-export": "error",
    "typescript/no-var-requires": "off",
    "typescript/no-wrapper-object-types": "error",
    "typescript/non-nullable-type-assertion-style": "error",
    "typescript/only-throw-error": ["error", { allowThrowingAny: false }],
    "typescript/parameter-properties": ["error", { prefer: "class-property" }],
    "typescript/prefer-as-const": "error",
    "typescript/prefer-enum-initializers": "error",
    "typescript/prefer-find": "error",
    "typescript/prefer-for-of": "error",
    "typescript/prefer-function-type": "error",
    "typescript/prefer-includes": "error",
    "typescript/prefer-literal-enum-member": "error",
    "typescript/prefer-namespace-keyword": "off",
    "typescript/prefer-nullish-coalescing": ["error", { ignoreConditionalTests: false }],
    "typescript/prefer-promise-reject-errors": "error",
    "typescript/prefer-readonly": "error",
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/prefer-reduce-type-parameter": "error",
    "typescript/prefer-regexp-exec": "error",
    "typescript/prefer-return-this-type": "error",
    "typescript/prefer-string-starts-ends-with": "error",
    "typescript/prefer-ts-expect-error": "error",
    "typescript/promise-function-async": "error",
    "typescript/related-getter-setter-pairs": "error",
    "typescript/require-array-sort-compare": ["error", { ignoreStringArrays: true }],
    "typescript/require-await": "error",
    "typescript/restrict-plus-operands": "error",
    "typescript/restrict-template-expressions": [
      "error",
      {
        allowAny: false,
        allowBoolean: false,
        allowNever: false,
        allowNullish: false,
        allowNumber: true,
      },
    ],
    "typescript/return-await": ["error", "in-try-catch"],
    "typescript/strict-boolean-expressions": "error",
    "typescript/strict-void-return": "error",
    "typescript/switch-exhaustiveness-check": [
      "error",
      {
        allowDefaultCaseForExhaustiveSwitch: false,
        considerDefaultExhaustiveForUnions: true,
        requireDefaultForNonUnion: true,
      },
    ],
    "typescript/triple-slash-reference": "error",
    "typescript/unbound-method": "error",
    "typescript/unified-signatures": "error",
    "typescript/use-unknown-in-catch-callback-variable": "error",
    "unicorn/catch-error-name": "error",
    "unicorn/consistent-assert": "error",
    "unicorn/consistent-date-clone": "error",
    "unicorn/consistent-empty-array-spread": "error",
    "unicorn/consistent-existence-index-check": "error",
    "unicorn/consistent-function-scoping": "error",
    "unicorn/consistent-template-literal-escape": "error",
    "unicorn/custom-error-definition": "error",
    "unicorn/empty-brace-spaces": "off", // oxfmt prints `{}` / `function f() {}`
    "unicorn/error-message": "error",
    "unicorn/escape-case": "error",
    "unicorn/explicit-length-check": "error",
    "unicorn/explicit-timer-delay": ["error", "never"],
    "unicorn/filename-case": "off",
    "unicorn/import-style": "off",
    "unicorn/max-nested-calls": "off",
    "unicorn/new-for-builtins": "error",
    "unicorn/no-abusive-eslint-disable": "error",
    "unicorn/no-accessor-recursion": "error",
    "unicorn/no-anonymous-default-export": "off",
    "unicorn/no-array-callback-reference": "off",
    "unicorn/no-array-fill-with-reference-type": "error",
    "unicorn/no-array-for-each": "error",
    "unicorn/no-array-method-this-argument": "error",
    "unicorn/no-array-reduce": "error",
    "unicorn/no-array-reverse": "error",
    "unicorn/no-array-sort": ["error"],
    "unicorn/no-await-expression-member": "error",
    "unicorn/no-await-in-promise-methods": "error",
    "unicorn/no-confusing-array-with": "error",
    "unicorn/no-console-spaces": "error",
    "unicorn/no-document-cookie": "error",
    "unicorn/no-empty-file": "error",
    "unicorn/no-hex-escape": "error",
    "unicorn/no-immediate-mutation": "error",
    "unicorn/no-instanceof-array": "error",
    "unicorn/no-instanceof-builtins": "error",
    "unicorn/no-invalid-fetch-options": "error",
    "unicorn/no-invalid-remove-event-listener": "error",
    "unicorn/no-length-as-slice-end": "error",
    "unicorn/no-lonely-if": "error",
    "unicorn/no-magic-array-flat-depth": "error",
    "unicorn/no-negated-condition": "error",
    "unicorn/no-negation-in-equality-check": "error",
    "unicorn/no-nested-ternary": "error",
    "unicorn/no-new-array": "error",
    "unicorn/no-new-buffer": "error",
    "unicorn/no-null": "off",
    "unicorn/no-object-as-default-parameter": "error",
    "unicorn/no-process-exit": "error",
    "unicorn/no-single-promise-in-promise-methods": "error",
    "unicorn/no-static-only-class": "error",
    "unicorn/no-thenable": "error",
    "unicorn/no-this-assignment": "error",
    "unicorn/no-typeof-undefined": ["error", { checkGlobalVariables: true }],
    "unicorn/no-unnecessary-array-flat-depth": "error",
    "unicorn/no-unnecessary-array-splice-count": "error",
    "unicorn/no-unnecessary-await": "error",
    "unicorn/no-unnecessary-slice-end": "error",
    "unicorn/no-unreadable-array-destructuring": "error",
    "unicorn/no-unreadable-iife": "error",
    "unicorn/no-useless-collection-argument": "error",
    "unicorn/no-useless-error-capture-stack-trace": "error",
    "unicorn/no-useless-fallback-in-spread": "error",
    "unicorn/no-useless-length-check": "error",
    "unicorn/no-useless-promise-resolve-reject": "error",
    "unicorn/no-useless-spread": "error",
    "unicorn/no-useless-switch-case": "error",
    "unicorn/no-useless-undefined": "off",
    "unicorn/no-zero-fractions": "error",
    "unicorn/number-literal-case": "error",
    "unicorn/numeric-separators-style": ["error", { onlyIfContainsSeparator: true }],
    "unicorn/prefer-add-event-listener": "error",
    "unicorn/prefer-array-find": "error",
    "unicorn/prefer-array-flat": "error",
    "unicorn/prefer-array-flat-map": "error",
    "unicorn/prefer-array-index-of": "error",
    "unicorn/prefer-array-some": "error",
    "unicorn/prefer-at": "error",
    "unicorn/prefer-bigint-literals": "off",
    "unicorn/prefer-blob-reading-methods": "error",
    "unicorn/prefer-class-fields": "error",
    "unicorn/prefer-classlist-toggle": "error",
    "unicorn/prefer-code-point": "error",
    "unicorn/prefer-date-now": "error",
    "unicorn/prefer-default-parameters": "error",
    "unicorn/prefer-dom-node-append": "error",
    "unicorn/prefer-dom-node-dataset": "error",
    "unicorn/prefer-dom-node-remove": "error",
    "unicorn/prefer-dom-node-text-content": "error",
    "unicorn/prefer-event-target": "error",
    "unicorn/prefer-export-from": "error",
    "unicorn/prefer-global-this": "error",
    "unicorn/prefer-import-meta-properties": "error",
    "unicorn/prefer-includes": "error",
    "unicorn/prefer-keyboard-event-key": "error",
    "unicorn/prefer-logical-operator-over-ternary": "error",
    "unicorn/prefer-math-min-max": "error",
    "unicorn/prefer-math-trunc": "error",
    "unicorn/prefer-modern-dom-apis": "error",
    "unicorn/prefer-modern-math-apis": "error",
    "unicorn/prefer-module": "error",
    "unicorn/prefer-native-coercion-functions": "error",
    "unicorn/prefer-negative-index": "error",
    "unicorn/prefer-node-protocol": "error",
    "unicorn/prefer-number-coercion": "error",
    "unicorn/prefer-number-properties": [
      "error",
      {
        checkInfinity: true,
        checkNaN: true,
      },
    ],
    "unicorn/prefer-object-from-entries": "error",
    "unicorn/prefer-optional-catch-binding": "error",
    "unicorn/prefer-prototype-methods": "error",
    "unicorn/prefer-query-selector": "error",
    "unicorn/prefer-reflect-apply": "error",
    "unicorn/prefer-regexp-test": "error",
    "unicorn/prefer-response-static-json": "error",
    "unicorn/prefer-set-has": "error",
    "unicorn/prefer-set-size": "error",
    "unicorn/prefer-single-call": "error",
    "unicorn/prefer-spread": "error",
    "unicorn/prefer-string-raw": "error",
    "unicorn/prefer-string-replace-all": "error",
    "unicorn/prefer-string-slice": "error",
    "unicorn/prefer-string-starts-ends-with": "error",
    "unicorn/prefer-string-trim-start-end": "error",
    "unicorn/prefer-structured-clone": "error",
    "unicorn/prefer-ternary": ["error", "always"],
    "unicorn/prefer-top-level-await": "error",
    "unicorn/prefer-type-error": "error",
    "unicorn/relative-url-style": ["error", "never"],
    "unicorn/require-array-join-separator": "error",
    "unicorn/require-module-attributes": "error",
    "unicorn/require-module-specifiers": "error",
    "unicorn/require-number-to-fixed-digits-argument": "error",
    "unicorn/require-post-message-target-origin": "error",
    "unicorn/switch-case-braces": ["error", "avoid"],
    "unicorn/switch-case-break-position": "error",
    "unicorn/text-encoding-identifier-case": "error",
    "unicorn/throw-new-error": "error",
    "vitest/consistent-each-for": "off",
    "vitest/consistent-test-filename": "off",
    "vitest/consistent-test-it": "off",
    "vitest/consistent-vitest-vi": "off",
    "vitest/expect-expect": "off",
    "vitest/hoisted-apis-on-top": "off",
    "vitest/max-expects": "off",
    "vitest/max-nested-describe": "off",
    "vitest/no-alias-methods": "off",
    "vitest/no-commented-out-tests": "off",
    "vitest/no-conditional-expect": "off",
    "vitest/no-conditional-in-test": "off",
    "vitest/no-conditional-tests": "off",
    "vitest/no-disabled-tests": "off",
    "vitest/no-duplicate-hooks": "off",
    "vitest/no-focused-tests": "off",
    "vitest/no-hooks": "off",
    "vitest/no-identical-title": "off",
    "vitest/no-import-node-test": "off",
    "vitest/no-importing-vitest-globals": "off",
    "vitest/no-interpolation-in-snapshots": "off",
    "vitest/no-large-snapshots": "off",
    "vitest/no-mocks-import": "off",
    "vitest/no-restricted-matchers": "off",
    "vitest/no-restricted-vi-methods": "off",
    "vitest/no-standalone-expect": "off",
    "vitest/no-test-prefixes": "off",
    "vitest/no-test-return-statement": "off",
    "vitest/no-unneeded-async-expect-function": "off",
    "vitest/padding-around-after-all-blocks": "off",
    "vitest/padding-around-test-blocks": "off",
    "vitest/prefer-called-exactly-once-with": "off",
    "vitest/prefer-called-once": "off",
    "vitest/prefer-called-times": "off",
    "vitest/prefer-called-with": "off",
    "vitest/prefer-comparison-matcher": "off",
    "vitest/prefer-describe-function-title": "off",
    "vitest/prefer-each": "off",
    "vitest/prefer-equality-matcher": "off",
    "vitest/prefer-expect-assertions": "off",
    "vitest/prefer-expect-resolves": "off",
    "vitest/prefer-expect-type-of": "off",
    "vitest/prefer-hooks-in-order": "off",
    "vitest/prefer-hooks-on-top": "off",
    "vitest/prefer-import-in-mock": "off",
    "vitest/prefer-importing-vitest-globals": "off",
    "vitest/prefer-lowercase-title": "off",
    "vitest/prefer-mock-promise-shorthand": "off",
    "vitest/prefer-mock-return-shorthand": "off",
    "vitest/prefer-snapshot-hint": "off",
    "vitest/prefer-spy-on": "off",
    "vitest/prefer-strict-boolean-matchers": "off",
    "vitest/prefer-strict-equal": "off",
    "vitest/prefer-to-be": "off",
    "vitest/prefer-to-be-falsy": "off",
    "vitest/prefer-to-be-object": "off",
    "vitest/prefer-to-be-truthy": "off",
    "vitest/prefer-to-contain": "off",
    "vitest/prefer-to-have-been-called-times": "off",
    "vitest/prefer-to-have-length": "off",
    "vitest/prefer-todo": "off",
    "vitest/require-awaited-expect-poll": "off",
    "vitest/require-hook": "off",
    "vitest/require-local-test-context-for-concurrent-snapshots": "off",
    "vitest/require-mock-type-parameters": "off",
    "vitest/require-test-timeout": "off",
    "vitest/require-to-throw-message": "off",
    "vitest/require-top-level-describe": "off",
    "vitest/valid-describe-callback": "off",
    "vitest/valid-expect": "off",
    "vitest/valid-expect-in-promise": "off",
    "vitest/valid-title": "off",
    "vitest/warn-todo": "off",
  },
  overrides: [
    {
      files: ["**/*.d.{ts,cts,mts}", "**/*.test-d.{ts,cts,mts}"],
      rules: {
        "import/no-empty-named-blocks": "off",
        "import/no-unassigned-import": "off",
        "import/unambiguous": "off",
        "typescript/consistent-type-definitions": "off",
        "typescript/no-empty-object-type": "off",
        "typescript/no-restricted-types": "off",
        "typescript/no-useless-empty-export": "off",
        "unicorn/require-module-specifiers": "off",
      },
    },
    {
      files: ["**/*.test.{js,jsx,ts,tsx,cjs,cts,mjs,mts}", "**/*.test-d.{ts,cts,mts}"],
      excludeFiles: ["**/e2e/**"],
      rules: {
        "eslint/getter-return": "off",
        "eslint/no-empty-function": "off",
        "eslint/no-param-reassign": "off",
        "eslint/no-promise-executor-return": "off",
        "eslint/no-useless-assignment": "off",
        "import/no-unassigned-import": "off",
        "import/unambiguous": "off",
        "oxc/approx-constant": "off",
        "oxc/no-accumulating-spread": "off",
        "oxc/no-map-spread": "off",
        "promise/catch-or-return": "off",
        "promise/no-callback-in-promise": "off",
        "promise/no-promise-in-callback": "off",
        "promise/no-return-wrap": "off",
        "promise/prefer-await-to-then": "off",
        "eslint/no-console": "off",
        "typescript/ban-ts-comment": "off",
        "typescript/explicit-module-boundary-types": "off",
        "typescript/no-explicit-any": "off",
        "typescript/no-non-null-assertion": "off",
        "typescript/no-unsafe-type-assertion": "off",
        "typescript/strict-boolean-expressions": "off",
        "typescript/unbound-method": "off",
        "typescript/no-base-to-string": "off",
        "typescript/no-confusing-void-expression": "off",
        "typescript/no-extraneous-class": "off",
        "typescript/no-restricted-types": "off",
        "typescript/no-unsafe-argument": "off",
        "typescript/no-unsafe-assignment": "off",
        "typescript/no-unsafe-call": "off",
        "typescript/no-unsafe-declaration-merging": "off",
        "typescript/no-unsafe-enum-comparison": "off",
        "typescript/no-unsafe-function-type": "off",
        "typescript/no-unsafe-member-access": "off",
        "typescript/no-unsafe-return": "off",
        "typescript/no-unsafe-unary-minus": "off",
        "typescript/only-throw-error": "off",
        "typescript/restrict-template-expressions": "off",
        "typescript/strict-void-return": "off",
        "unicorn/consistent-function-scoping": "off",
        "unicorn/error-message": "off",
        "unicorn/no-array-fill-with-reference-type": "off",
        "unicorn/no-empty-file": "off",
        "unicorn/no-useless-promise-resolve-reject": "off",
        "unicorn/prefer-single-call": "off",
        "vitest/consistent-each-for": [
          "error",
          {
            test: "each",
            describe: "each",
            it: "each",
            suite: "each",
          },
        ],
        "vitest/consistent-vitest-vi": "error",
        "vitest/expect-expect": "error",
        "vitest/hoisted-apis-on-top": "error",
        "vitest/no-commented-out-tests": "error",
        "vitest/no-conditional-expect": "error",
        "vitest/no-conditional-in-test": "error",
        "vitest/no-disabled-tests": "error",
        "vitest/no-duplicate-hooks": "error",
        "vitest/no-focused-tests": "error",
        "vitest/no-identical-title": "error",
        "vitest/no-import-node-test": "error",
        "vitest/no-interpolation-in-snapshots": "error",
        "vitest/no-mocks-import": "error",
        "vitest/no-standalone-expect": "error",
        "vitest/no-test-return-statement": "error",
        "vitest/no-unneeded-async-expect-function": "error",
        "vitest/padding-around-after-all-blocks": "error",
        "vitest/padding-around-test-blocks": "error",
        "vitest/prefer-called-exactly-once-with": "error",
        "vitest/prefer-called-times": "error",
        "vitest/prefer-comparison-matcher": "error",
        "vitest/prefer-describe-function-title": "error",
        "vitest/prefer-each": "error",
        "vitest/prefer-equality-matcher": "error",
        "vitest/prefer-expect-resolves": "error",
        "vitest/prefer-expect-type-of": "error",
        "vitest/prefer-hooks-in-order": "error",
        "vitest/prefer-hooks-on-top": "error",
        "vitest/prefer-mock-promise-shorthand": "error",
        "vitest/prefer-mock-return-shorthand": "error",
        "vitest/prefer-strict-boolean-matchers": "error",
        "vitest/prefer-strict-equal": "error",
        "vitest/prefer-to-be": "error",
        "vitest/prefer-to-be-object": "error",
        "vitest/prefer-to-contain": "error",
        "vitest/prefer-to-have-been-called-times": "error",
        "vitest/prefer-to-have-length": "error",
        "vitest/prefer-todo": "error",
        "vitest/require-awaited-expect-poll": "error",
        "vitest/require-local-test-context-for-concurrent-snapshots": "error",
        "vitest/require-to-throw-message": "error",
        "vitest/valid-describe-callback": "error",
        "vitest/valid-expect": "error",
        "vitest/valid-expect-in-promise": "error",
        "vitest/valid-title": "error",
        "vitest/warn-todo": "error",
      },
    },
    {
      files: ["**/*.config.{js,ts,cjs,cts,mjs,mts}", "**/*.setup.{js,ts,cjs,cts,mjs,mts}"],
      rules: {
        "import/no-anonymous-default-export": ["error", { allowObject: true }],
        "import/no-unassigned-import": "off",
        "import/unambiguous": "off",
        "typescript/no-useless-empty-export": "off",
        "unicorn/no-empty-file": "off",
      },
    },
  ],
} satisfies OxlintConfig;
