import type { OxlintConfig } from "oxlint";

import { config } from "./config.ts";
import { merge } from "./merge.ts";

const overlay = {
  plugins: ["jsx-a11y", "react", "react-perf"],
  rules: {
    "jsx-a11y/alt-text": "error",
    "jsx-a11y/anchor-ambiguous-text": "error",
    "jsx-a11y/anchor-has-content": "error",
    "jsx-a11y/anchor-is-valid": "error",
    "jsx-a11y/aria-activedescendant-has-tabindex": "error",
    "jsx-a11y/aria-props": "error",
    "jsx-a11y/aria-proptypes": "error",
    "jsx-a11y/aria-role": "error",
    "jsx-a11y/aria-unsupported-elements": "error",
    "jsx-a11y/autocomplete-valid": "error",
    "jsx-a11y/click-events-have-key-events": "error",
    "jsx-a11y/control-has-associated-label": "error",
    "jsx-a11y/heading-has-content": "error",
    "jsx-a11y/html-has-lang": "error",
    "jsx-a11y/iframe-has-title": "error",
    "jsx-a11y/img-redundant-alt": "error",
    "jsx-a11y/interactive-supports-focus": "error",
    "jsx-a11y/label-has-associated-control": "error",
    "jsx-a11y/lang": "error",
    "jsx-a11y/media-has-caption": "off",
    "jsx-a11y/mouse-events-have-key-events": "error",
    "jsx-a11y/no-access-key": "error",
    "jsx-a11y/no-aria-hidden-on-focusable": "error",
    "jsx-a11y/no-autofocus": "error",
    "jsx-a11y/no-distracting-elements": "error",
    "jsx-a11y/no-interactive-element-to-noninteractive-role": "error",
    "jsx-a11y/no-noninteractive-element-interactions": "error",
    "jsx-a11y/no-noninteractive-element-to-interactive-role": "error",
    "jsx-a11y/no-noninteractive-tabindex": "error",
    "jsx-a11y/no-redundant-roles": "error",
    "jsx-a11y/no-static-element-interactions": "error",
    "jsx-a11y/prefer-tag-over-role": "error",
    "jsx-a11y/role-has-required-aria-props": "error",
    "jsx-a11y/role-supports-aria-props": "error",
    "jsx-a11y/scope": "error",
    "jsx-a11y/tabindex-no-positive": "error",
    "react-perf/jsx-no-jsx-as-prop": "off",
    "react-perf/jsx-no-new-array-as-prop": "error",
    "react-perf/jsx-no-new-function-as-prop": "off",
    "react-perf/jsx-no-new-object-as-prop": "off",
    "react/button-has-type": "error",
    "react/checked-requires-onchange-or-readonly": "error",
    "react/display-name": "off",
    "react/exhaustive-deps": "error",
    "react/forbid-component-props": "off",
    "react/forbid-dom-props": "off",
    "react/forbid-elements": "off",
    "react/forward-ref-uses-ref": "off",
    "react/function-component-definition": "off",
    "react/hook-use-state": "error",
    "react/iframe-missing-sandbox": "error",
    "react/jsx-boolean-value": "error",
    "react/jsx-curly-brace-presence": [
      "error",
      {
        children: "never",
        propElementValues: "always",
        props: "never",
      },
    ],
    "react/jsx-filename-extension": ["error", { extensions: [".jsx", ".tsx"] }],
    "react/jsx-fragments": "error",
    "react/jsx-handler-names": "error",
    "react/jsx-key": "error",
    "react/jsx-max-depth": "off",
    "react/jsx-no-comment-textnodes": "error",
    "react/jsx-no-constructed-context-values": "error",
    "react/jsx-no-duplicate-props": "error",
    "react/jsx-no-literals": "off",
    "react/jsx-no-script-url": "error",
    "react/jsx-no-target-blank": ["error", { warnOnSpreadAttributes: true }],
    "react/jsx-no-undef": "error",
    "react/jsx-no-useless-fragment": "error",
    "react/jsx-pascal-case": "error",
    "react/jsx-props-no-spread-multi": "error",
    "react/jsx-props-no-spreading": "off",
    "react/no-array-index-key": "error",
    "react/no-children-prop": "error",
    "react/no-clone-element": "off",
    "react/no-danger": "error",
    "react/no-danger-with-children": "error",
    "react/no-did-mount-set-state": "off",
    "react/no-did-update-set-state": "off",
    "react/no-direct-mutation-state": "off",
    "react/no-find-dom-node": "off",
    "react/no-is-mounted": "off",
    "react/no-multi-comp": "off",
    "react/no-namespace": "error",
    "react/no-object-type-as-default-prop": "error",
    "react/no-react-children": "off",
    "react/no-redundant-should-component-update": "off",
    "react/no-render-return-value": "off",
    "react/no-set-state": "off",
    "react/no-string-refs": "off",
    "react/no-this-in-sfc": "off",
    "react/no-unescaped-entities": "error",
    "react/no-unknown-property": "error",
    "react/no-unsafe": "error",
    "react/no-unstable-nested-components": "error",
    "react/no-will-update-set-state": "off",
    "react/only-export-components": "error",
    "react/prefer-es6-class": "off",
    "react/prefer-function-component": "off",
    "react/capitalized-calls": "error",
    "react/error-boundaries": "error",
    "react/exhaustive-effect-dependencies": "error",
    "react/globals": "error",
    "react/hooks": "error",
    "react/immutability": "error",
    "react/incompatible-library": "error",
    "react/invariant": "error",
    "react/memo-dependencies": "error",
    "react/no-deriving-state-in-effects": "error",
    "react/preserve-manual-memoization": "error",
    "react/purity": "error",
    "react/refs": "error",
    "react/rule-suppression": "error",
    "react/set-state-in-effect": "error",
    "react/set-state-in-render": "error",
    "react/static-components": "error",
    "react/syntax": "error",
    "react/todo": "off",
    "react/unsupported-syntax": "error",
    "react/use-memo": "error",
    "react/void-use-memo": "error",
    "react/react-in-jsx-scope": "off",
    "react/require-render-return": "off",
    "react/rules-of-hooks": "error",
    "react/self-closing-comp": "error",
    "react/state-in-constructor": "off",
    "react/style-prop-object": "error",
    "react/void-dom-elements-no-children": "error",
  },
  overrides: [
    {
      files: ["**/*.test.{js,jsx,ts,tsx,cjs,cts,mjs,mts}", "**/*.test-d.{ts,cts,mts}"],
      excludeFiles: ["**/e2e/**"],
      rules: {
        "jsx-a11y/alt-text": "off",
        "jsx-a11y/anchor-ambiguous-text": "off",
        "jsx-a11y/anchor-has-content": "off",
        "jsx-a11y/anchor-is-valid": "off",
        "jsx-a11y/click-events-have-key-events": "error",
        "jsx-a11y/control-has-associated-label": "off",
        "jsx-a11y/heading-has-content": "off",
        "jsx-a11y/html-has-lang": "off",
        "jsx-a11y/iframe-has-title": "off",
        "jsx-a11y/interactive-supports-focus": "off",
        "jsx-a11y/label-has-associated-control": "off",
        "jsx-a11y/lang": "off",
        "jsx-a11y/mouse-events-have-key-events": "error",
        "jsx-a11y/no-access-key": "off",
        "jsx-a11y/no-autofocus": "off",
        "jsx-a11y/no-distracting-elements": "off",
        "jsx-a11y/no-interactive-element-to-noninteractive-role": "off",
        "jsx-a11y/no-noninteractive-element-interactions": "error",
        "jsx-a11y/no-noninteractive-element-to-interactive-role": "off",
        "jsx-a11y/no-noninteractive-tabindex": "off",
        "jsx-a11y/no-redundant-roles": "off",
        "jsx-a11y/no-static-element-interactions": "off",
        "jsx-a11y/prefer-tag-over-role": "off",
        "jsx-a11y/scope": "off",
        "jsx-a11y/tabindex-no-positive": "off",
        "react-perf/jsx-no-new-array-as-prop": "off",
        "react/button-has-type": "off",
        "react/checked-requires-onchange-or-readonly": "off",
        "react/jsx-no-target-blank": "off",
        "react/jsx-no-useless-fragment": "off",
        "react/no-array-index-key": "off",
        "react/no-children-prop": "off",
        "react/no-danger": "off",
        "react/no-object-type-as-default-prop": "off",
        "react/no-unstable-nested-components": "error",
      },
    },
  ],
} satisfies OxlintConfig;

export const react = merge(config, overlay);
